version: "3.8"
services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - NODE_ENV=development
    volumes:
      - ".:/app"
    depends_on:
      - db
      - vite

  vite:
    build: .
    command: bin/vite dev
    ports:
      - "3036:3036"
    volumes:
      - ".:/app"
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres