services:
  web:
    build: .
    command: sh -c "bin/rails db:migrate && bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - NODE_ENV=development
    volumes:
      - ".:/app" # Syncs your local files with the container
    depends_on:
      - db
      - vite

  vite:
    build: .
    command: sh -c "yarn install && bin/vite dev"
    ports:
      - "3036:3036"
    volumes:
      - ".:/app" # Syncs your local files with the container
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: