default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost # Service name from docker-compose.yml

development:
  <<: *default
  database: face_app_development

test:
  <<: *default
  database: face_app_test

production:
  <<: *default
  database: face_app_production
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %> # Use environment variable in production